[theme]
primaryColor = "#00FFAA"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E232D"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
